INSERT INTO pages (title, slug, content) VALUES ('Home', '/public/index.php', '');
INSERT INTO pages (title, slug, content) VALUES ('About IIBH', '/public/about-us/about-iibh.php', '');
INSERT INTO pages (title, slug, content) VALUES ('About IIDI', '/public/about-us/about-iidi.php', '');
INSERT INTO pages (title, slug, content) VALUES ('Board of Directors', '/public/about-us/board-of-directors.php', '');
INSERT INTO pages (title, slug, content) VALUES ('Management Team', '/public/about-us/management-team.php', '');
INSERT INTO pages (title, slug, content) VALUES ('Committees', '/public/about-us/committees.php', '');
INSERT INTO pages (title, slug, content) VALUES ('Group Companies', '/public/about-us/group-companies.php', '');
INSERT INTO pages (title, slug, content) VALUES ('Bullion - Client', '/public/bullion/client.php', '');
INSERT INTO pages (title, slug, content) VALUES ('Bullion - Member', '/public/bullion/member.php', '');
INSERT INTO pages (title, slug, content) VALUES ('Bullion - Vault Manager', '/public/bullion/vault-manager.php', '');
INSERT INTO pages (title, slug, content) VALUES ('Bullion - Knowledge Centre', '/public/bullion/knowledge-centre.php', '');
INSERT INTO pages (title, slug, content) VALUES ('Bullion - Using', '/public/bullion/bullion-using.php', '');
INSERT INTO pages (title, slug, content) VALUES ('Securities - Become DP', '/public/securities/how-to-become-dp.php', '');
INSERT INTO pages (title, slug, content) VALUES ('Securities - List of DPs', '/public/securities/list-of-iidi-dps.php', '');
INSERT INTO pages (title, slug, content) VALUES ('Securities - ISIN', '/public/securities/security-isin.php', '');
INSERT INTO pages (title, slug, content) VALUES ('Investor - Annual Reports', '/public/investor-relations/annual-reports.php', '');
INSERT INTO pages (title, slug, content) VALUES ('Investor - Complaint Handling', '/public/investor-relations/complaint-handling.php', '');
INSERT INTO pages (title, slug, content) VALUES ('Investor - Other Downloads', '/public/investor-relations/other-downloads.php', '');
INSERT INTO pages (title, slug, content) VALUES ('Circulars - Bullion', '/public/circulars/bullion-circulars.php', '');
INSERT INTO pages (title, slug, content) VALUES ('Circulars - Securities', '/public/circulars/securities-circulars.php', '');
INSERT INTO pages (title, slug, content) VALUES ('Circulars - Tenders', '/public/circulars/tenders.php', '');
INSERT INTO pages (title, slug, content) VALUES ('Regulations - IFSC Authority', '/public/regulations/ifsc-authority.php', '');
INSERT INTO pages (title, slug, content) VALUES ('Regulations - IIDI', '/public/regulations/iidi.php', '');
INSERT INTO pages (title, slug, content) VALUES ('Contact Us', '/public/contact-us.php', '');
